# Generated by Django 5.0.3 on 2024-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('hobby', 'Hobby'), ('food', 'Food'), ('programming', 'Programming')], default='hobby', max_length=20),
        ),
    ]
