# Generated by Django 5.0.4 on 2024-04-10 06:54

import pytz.tzinfo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_published_date_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=pytz.tzinfo.DstTzInfo.localize),
        ),
    ]
