# Generated by Django 5.0.4 on 2024-06-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
