# Generated by Django 5.0.4 on 2024-06-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ourgame', '0003_alter_record_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
