# Generated by Django 5.0.4 on 2024-05-02 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image_url_alter_post_last_viewed_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_viewed_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 22, 39, 42, 22843)),
        ),
    ]
