# Generated by Django 5.0.4 on 2024-04-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
