# Generated by Django 5.0.4 on 2024-04-05 15:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='due_date',
        ),
        migrations.AddField(
            model_name='post',
            name='selected_date',
            field=models.DateField(default=app.models.default_selected_date),
        ),
    ]
