# Generated by Django 5.0.4 on 2024-04-06 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_selecteddate_remove_post_due_date_post_selected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
